KTB-20 migration Kotlinx.Serialization
vvaganov/KotlinTelegramBot pull request #17
Opened 2024-08-02 12:04 UTC by vvaganov

2024-08-04 09:35 UTC, danelyan requested changes
1. Технически все выглядит отлично. Но давай немного порефакторим.
Давай вынесем всю логику отвечающую за работу с API телеграма в класс TelegramBotService. Разместим его в отдельном файле.
В конструктор класса передадим токен. Внутри класса создадим httpClient через который будет осуществлять сетевые вызовы. Урлы вынесем к константы.

2. Нам нужно переименовать KTB-20 в KTB-21. Номер задачи не соответствует номеру на платформе

2024-08-06 07:47 UTC, vvaganov commented
Фридон, привет!
Это все на данынй момент что мой мозг способен решить:)
По порядку
Наверное функции fun getUpdateDataClass не место в классе TelegramBot
Вообще наверно, все дата классы эту функцию и т.п. подобное нужно вынести в отдельный файл (класс)

Не смог решить как вынести URL в константы, как передавать переменные в этом случае, не сходится у меня пока.
Подскажи где поискать инфу по этому поводу.
Дублирующая функция из TelegramBotService уберется после решения этого вопроса.

2024-08-07 19:07 UTC, kaznikit commented
> Фридон, привет! Это все на данынй момент что мой мозг способен решить:) По порядку Наверное функции fun getUpdateDataClass не место в классе TelegramBot Вообще наверно, все дата классы эту функцию и т.п. подобное нужно вынести в отдельный файл (класс)
> 
> Не смог решить как вынести URL в константы, как передавать переменные в этом случае, не сходится у меня пока. Подскажи где поискать инфу по этому поводу. Дублирующая функция из TelegramBotService уберется после решения этого вопроса.

Привет! Я Никита и теперь я за Фридона)
По поводу функции getUpdateDataClass, вполне нормально что она находится в TelegramBot

Попробуй вынести в константу BASE_URL https://api.telegram.org/bot, тогда формирование например urlGetUpdates будет происходить таким образом: 
`val urlGetUpdates = "$BASE_URL$botToken/getUpdates?offset=$updateId"`

2024-08-10 05:59 UTC, vvaganov commented
Никита, привет!
Избавился от одной функции отправки.
Все работает. Но мне кажется слишком много зависимостей передается из функции в функцию.

2024-08-11 07:02 UTC, kaznikit commented
> Никита, привет! Избавился от одной функции отправки. Все работает. Но мне кажется слишком много зависимостей передается из функции в функцию.

Согласен, выглядит так что функции sendMessage, sendQuestion и sendMenu стоит перенести в TelegramBotService, тогда не придется передавать дополнительно пару параметров. Давай этот мр аппрувну, а это поправим в следующих ПРах

2024-08-11 07:02 UTC, kaznikit approved these changes

2024-08-15 04:25 UTC, merged