KTB-04 we parse the file and create both objects in a loop, output th…
vvaganov/KotlinTelegramBot pull request #2
Opened 2024-06-29 09:25 UTC by vvaganov

…em to the console

Не совсем уверен в правильности реализации correctAnswersCount. Думаю зачем нам счетчик в конструкторе. Но как спарсить файл и присвоить значение этой переменной в цикле, если ее из конструктора вынести,  я так и не додумался. С элвис оператором тоже не понятно мне, вроде он там и не к месту в текущей реализации. Ну в общем пока так.

2024-06-29 15:06 UTC, danelyan requested changes

2024-06-29 15:06 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        dictionary.add(Word(split[0], split[1], split[2].toInt() ?: 0))
toInt() приведет к ошибке, если в текстовом файле будет не число. Лучше `toIntOrNull()`

2024-06-29 15:07 UTC, danelyan requested changes
> Не совсем уверен в правильности реализации correctAnswersCount. Думаю зачем нам счетчик в конструкторе. Но как спарсить файл и присвоить значение этой переменной в цикле, если ее из конструктора вынести, я так и не додумался. 

Вроде бы все корректно, ты просто загружаешь значение из файла

2024-06-30 05:13 UTC, vvaganov commented on src/main/kotlin/Main.kt
> +        dictionary.add(Word(split[0], split[1], split[2].toInt() ?: 0))
я понял, если не Int то null, а дальше если null то уже элвис подставляет 0. Все так просто оказывается:)

2024-07-01 11:29 UTC, danelyan approved these changes

2024-07-01 13:21 UTC, merged