KTB-12 Get a telegram bot token and execute basic HTTP requests
vvaganov/KotlinTelegramBot pull request #9
Opened 2024-07-09 13:29 UTC by vvaganov

2024-07-10 05:26 UTC, danelyan requested changes

2024-07-10 05:26 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    val urlGetMi = "https://api.telegram.org/bot$botToken/getMe"
опечатка в названии переменной

2024-07-10 05:26 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    println("getMy - ${response.body()}")
опечатка в println

2024-07-10 06:07 UTC, vvaganov commented on src/main/kotlin/Telegram.kt
> +    println("getMy - ${response.body()}")
исправлено

2024-07-13 07:45 UTC, danelyan approved these changes

2024-07-13 11:44 UTC, merged